"""initial migration

Revision ID: 07081f71511d
Revises: c84fe97e68dc
Create Date: 2024-07-19 05:34:34.159290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07081f71511d'
down_revision = 'c84fe97e68dc'
branch_labels = None
depends_on = None


def upgrade(): 
 
    #op.drop_table('educational_language')  
    

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('course_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spoken_language', ['educational_language_id'], ['id'])
        batch_op.drop_column('external_id')

    with op.batch_alter_table('course_foreign_language_relation', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('course_level_relation', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('exoneration', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('external_school', schema=None) as batch_op:
        batch_op.drop_constraint('external_school_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spoken_language', ['educational_language_id'], ['id'])

    with op.batch_alter_table('foreign_language', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('lead_status', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.alter_column('degree_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('mark_system', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('nationality', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint('school_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spoken_language', ['educational_language_id'], ['id'])
        batch_op.drop_column('external_id')

    with op.batch_alter_table('subdomain', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('subject_weight_system', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('visa', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('subject_weight_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('subdomain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('school_ibfk_3', 'educational_language', ['educational_language_id'], ['id'])

    with op.batch_alter_table('nationality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('mark_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.alter_column('degree_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    with op.batch_alter_table('lead_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('foreign_language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('external_school', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('external_school_ibfk_2', 'educational_language', ['educational_language_id'], ['id'])

    with op.batch_alter_table('exoneration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('course_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('course_level_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('course_foreign_language_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_ibfk_4', 'educational_language', ['educational_language_id'], ['id'])

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subregion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency_symbol', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('currency_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('translations', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('timezones', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('emojiU', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('tld', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('native', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('iso3', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('capital', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.add_column(sa.Column('subregion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numeric_code', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('phonecode', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('emoji', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('currency', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('country_continent_final', 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key('country_subregion_final', 'subregions', ['subregion_id'], ['id'])
        batch_op.create_index('country_subregion', ['subregion_id'], unique=False)
        batch_op.create_index('country_continent', ['region_id'], unique=False)
        batch_op.alter_column('iso2',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text("'2014-01-01 06:31:01'"), nullable=False))
        batch_op.add_column(sa.Column('state_code', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country_code', mysql.CHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False))
        batch_op.create_foreign_key('cities_ibfk_1', 'states', ['state_id'], ['id'])
        batch_op.create_index('cities_test_ibfk_2', ['country_id'], unique=False)
        batch_op.create_index('cities_test_ibfk_1', ['state_id'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('academic_year_organization', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    op.create_table('states',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('country_code', mysql.CHAR(length=2), nullable=False),
    sa.Column('fips_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('iso2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_region_final'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index('country_region', ['country_id'], unique=False)

    op.create_table('educational_language',
    sa.Column('id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('spoken_language_id', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='educational_language_ibfk_2'),
    sa.ForeignKeyConstraint(['spoken_language_id'], ['spoken_language.id'], name='educational_language_ibfk_1'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='educational_language_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    # ### end Alembic commands ###
