"""initial migration

Revision ID: 4fa381f3f6a3
Revises: 
Create Date: 2024-04-21 20:09:39.984944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa381f3f6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index('country_region')

    op.drop_table('states')
    op.drop_table('regions')
    with op.batch_alter_table('subregions', schema=None) as batch_op:
        batch_op.drop_index('subregion_continent')

    op.drop_table('subregions')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=255), nullable=True))
        batch_op.drop_index('cities_test_ibfk_1')
        batch_op.drop_index('cities_test_ibfk_2')
        batch_op.drop_constraint('cities_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('cities_ibfk_2', type_='foreignkey')
        batch_op.drop_column('state_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('wikiDataId')
        batch_op.drop_column('name')
        batch_op.drop_column('latitude')
        batch_op.drop_column('country_id')
        batch_op.drop_column('state_code')
        batch_op.drop_column('flag')
        batch_op.drop_column('country_code')
        batch_op.drop_column('longitude')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=255), nullable=True))
        batch_op.drop_index('country_continent')
        batch_op.drop_index('country_subregion')
        batch_op.drop_constraint('country_subregion_final', type_='foreignkey')
        batch_op.drop_constraint('country_continent_final', type_='foreignkey')
        batch_op.drop_column('iso2')
        batch_op.drop_column('timezones')
        batch_op.drop_column('numeric_code')
        batch_op.drop_column('flag')
        batch_op.drop_column('subregion_id')
        batch_op.drop_column('longitude')
        batch_op.drop_column('created_at')
        batch_op.drop_column('currency_name')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')
        batch_op.drop_column('phonecode')
        batch_op.drop_column('wikiDataId')
        batch_op.drop_column('region_id')
        batch_op.drop_column('nationality')
        batch_op.drop_column('capital')
        batch_op.drop_column('native')
        batch_op.drop_column('latitude')
        batch_op.drop_column('emoji')
        batch_op.drop_column('emojiU')
        batch_op.drop_column('translations')
        batch_op.drop_column('region')
        batch_op.drop_column('iso3')
        batch_op.drop_column('currency')
        batch_op.drop_column('tld')
        batch_op.drop_column('subregion')
        batch_op.drop_column('currency_symbol')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'nationality', ['nationality_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'passport', ['passport_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'lead_status', ['lead_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_symbol', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subregion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tld', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('iso3', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('translations', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('emojiU', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('emoji', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('native', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('capital', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.add_column(sa.Column('phonecode', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('currency_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('subregion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('numeric_code', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('timezones', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('iso2', mysql.CHAR(length=2), nullable=True))
        batch_op.create_foreign_key('country_continent_final', 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key('country_subregion_final', 'subregions', ['subregion_id'], ['id'])
        batch_op.create_index('country_subregion', ['subregion_id'], unique=False)
        batch_op.create_index('country_continent', ['region_id'], unique=False)
        batch_op.drop_column('reference')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text("'2014-01-01 06:31:01'"), nullable=False))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False))
        batch_op.add_column(sa.Column('country_code', mysql.CHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state_code', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('cities_ibfk_2', 'countries', ['country_id'], ['id'])
        batch_op.create_foreign_key('cities_ibfk_1', 'states', ['state_id'], ['id'])
        batch_op.create_index('cities_test_ibfk_2', ['country_id'], unique=False)
        batch_op.create_index('cities_test_ibfk_1', ['state_id'], unique=False)
        batch_op.drop_column('reference')

    op.create_table('subregions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('translations', mysql.TEXT(), nullable=True),
    sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='subregion_continent_final'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('subregions', schema=None) as batch_op:
        batch_op.create_index('subregion_continent', ['region_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('translations', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('states',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('country_code', mysql.CHAR(length=2), nullable=False),
    sa.Column('fips_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('iso2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_region_final'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index('country_region', ['country_id'], unique=False)

    # ### end Alembic commands ###
