"""initial migration

Revision ID: 74c9ba1a4afe
Revises: 07081f71511d
Create Date: 2024-07-19 12:30:55.583987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74c9ba1a4afe'
down_revision = '07081f71511d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index('country_region')

    op.drop_table('states')
    with op.batch_alter_table('subregions', schema=None) as batch_op:
        batch_op.drop_index('subregion_continent')

    op.drop_table('subregions')
    with op.batch_alter_table('academic_year_organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('value')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('cities_test_ibfk_1')
        batch_op.drop_index('cities_test_ibfk_2')
        batch_op.drop_constraint('cities_ibfk_1', type_='foreignkey')
        batch_op.drop_column('wikiDataId')
        batch_op.drop_column('created_at')
        batch_op.drop_column('state_code')
        batch_op.drop_column('longitude')
        batch_op.drop_column('country_code')
        batch_op.drop_column('flag')
        batch_op.drop_column('state_id')
        batch_op.drop_column('latitude')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('iso2',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               nullable=False)
        batch_op.drop_index('country_continent')
        batch_op.drop_index('country_subregion')
        batch_op.drop_constraint('country_continent_final', type_='foreignkey')
        batch_op.drop_constraint('country_spoken_language', type_='foreignkey')
        batch_op.drop_constraint('country_subregion_final', type_='foreignkey')
        batch_op.drop_column('nationality')
        batch_op.drop_column('translations')
        batch_op.drop_column('currency_name')
        batch_op.drop_column('emoji')
        batch_op.drop_column('tld')
        batch_op.drop_column('created_at')
        batch_op.drop_column('most_popular_spoken_language_id')
        batch_op.drop_column('region_id')
        batch_op.drop_column('flag')
        batch_op.drop_column('phonecode')
        batch_op.drop_column('capital')
        batch_op.drop_column('latitude')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('wikiDataId')
        batch_op.drop_column('native')
        batch_op.drop_column('region')
        batch_op.drop_column('emojiU')
        batch_op.drop_column('subregion_id')
        batch_op.drop_column('currency')
        batch_op.drop_column('numeric_code')
        batch_op.drop_column('iso3')
        batch_op.drop_column('currency_symbol')
        batch_op.drop_column('longitude')
        batch_op.drop_column('subregion')
        batch_op.drop_column('timezones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezones', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('subregion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('currency_symbol', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('iso3', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('numeric_code', mysql.CHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('currency', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subregion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emojiU', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('native', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('capital', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('phonecode', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('most_popular_spoken_language_id', mysql.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('tld', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('emoji', mysql.VARCHAR(length=191), nullable=True))
        batch_op.add_column(sa.Column('currency_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('translations', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nationality', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('country_subregion_final', 'subregions', ['subregion_id'], ['id'])
        batch_op.create_foreign_key('country_spoken_language', 'spoken_language', ['most_popular_spoken_language_id'], ['id'])
        batch_op.create_foreign_key('country_continent_final', 'regions', ['region_id'], ['id'])
        batch_op.create_index('country_subregion', ['subregion_id'], unique=False)
        batch_op.create_index('country_continent', ['region_id'], unique=False)
        batch_op.alter_column('iso2',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=False))
        batch_op.add_column(sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country_code', mysql.CHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=False))
        batch_op.add_column(sa.Column('state_code', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text("'2014-01-01 06:31:01'"), nullable=False))
        batch_op.add_column(sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'))
        batch_op.create_foreign_key('cities_ibfk_1', 'states', ['state_id'], ['id'])
        batch_op.create_index('cities_test_ibfk_2', ['country_id'], unique=False)
        batch_op.create_index('cities_test_ibfk_1', ['state_id'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('academic_year_organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('name')

    op.create_table('subregions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('translations', mysql.TEXT(), nullable=True),
    sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='subregion_continent_final'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('subregions', schema=None) as batch_op:
        batch_op.create_index('subregion_continent', ['region_id'], unique=False)

    op.create_table('states',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('country_code', mysql.CHAR(length=2), nullable=False),
    sa.Column('fips_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('iso2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='country_region_final'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index('country_region', ['country_id'], unique=False)

    op.create_table('regions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('translations', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('flag', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('wikiDataId', mysql.VARCHAR(length=255), nullable=True, comment='Rapid API GeoDB Cities'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
