"""initial migration

Revision ID: c84fe97e68dc
Revises: 
Create Date: 2024-06-11 01:02:47.236787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c84fe97e68dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)


    with op.batch_alter_table('lead_subject_relation', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.alter_column('degree_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('mark_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('nationality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('spoken_language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('subdomain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=8), nullable=True))
        batch_op.alter_column('level_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('subject_weight_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('traveling', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), autoincrement=True, nullable=True))

    with op.batch_alter_table('visa', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('traveling', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('subject_weight_system', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('level_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.drop_column('code')

    with op.batch_alter_table('subdomain', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('spoken_language', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('passport', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('nationality', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('mark_system', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('level', schema=None) as batch_op:
        batch_op.alter_column('degree_id',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    with op.batch_alter_table('lead_subject_relation', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)


    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)





  

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('academic_year_organization', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('external_id')




 

    # ### end Alembic commands ###
